version: "3.2"

services:
#MariaDB Container
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile-Mariadb
    container_name: mariadb
    hostname: mariadb
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - ./mariadb.env
    restart: always
    
#GLPI Container
  glpi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/www/html/glpi/:/var/www/html/glpi
    environment:
      - TIMEZONE=Europe/Brussels
      - VERSION_GLPI=0.0.9
    restart: always
