FROM mariadb:10.7

# Descargar el archivo utilizando curl y darle permisos de ejecución
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
RUN curl -o /docker-entrypoint-initdb.d/init.sh https://github.com/glpi-project-mu/docker-glpi/releases/download/1.0.0/dump.sql
RUN chmod +x /docker-entrypoint-initdb.d/init.sh
